# Dependencies
# - markdown:         redcarpet
highlighter:      rouge

# Permalinks
# - permalink:        pretty
# - relative_permalinks: true

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde

title: "Nelson Tam"
tagline: ""
description: "Follow <a href=\"https://micro.blog/nelson\">@nelson on Micro.blog</a>."
credits: "Follow <a href=\"https://micro.blog/nelson\">@nelson on Micro.blog</a>."
baseurl: ""
url: "https://nelson.micro.blog"
markdown: "kramdown"
username: "nelson"
microblog_user: "nelson"
permalink: "/:year/:month/:day/:title.html"
relative_permalinks: false
author: "Nelson Tam"
name: "Nelson Tam"
gravatar_hash: "4c00e0eed53f05d9510ec8ccb9c77158"
avatar: "https://micro.blog/nelson/avatar.jpg"
full_name: "Nelson Tam"
bio: ""
twitter_username: ""
github_username: ""
instagram_username: ""
paginate: 20
paginate_path: "/page/:num/"
timezone: "Pacific/Yap"
site_id: "1104"
gems: ["jekyll-paginate"]
itunes_category: "Society & Culture"
itunes_subcategory: "Personal Journals"